### ISSUE TITLE
Implement upvote downvote functionality

### ISSUE THREAD

**Issue by akhil-rasheed** [akhil-rasheed/hyperlocal#11]
API already implemented, integration required

1) increase/decrease count locally
2) call API

-----------------------
Make sure posts maintain upvote/downvote state even on refresh. Use upvoted users array, research optimal approach

**Comment by giri-madhan** [comment]
Hi @akhil-rasheed, where should this feature be implemented? Also, do we have a design for the upvote/downvote buttons?

**Comment by akhil-rasheed** [comment]
Hey @giri-madhan 
We appreciate your interest in contributing, but I have to mention that this is a repo for a university project with a few of my teammates. However, if you're still interested in contributing, I'll make some contribution guidelines later this week, and you can check back then!

**Comment by giri-madhan** [comment]
Sure @akhil-rasheed. Thank you!

**Comment by prithvi206** [comment]
@akhil-rasheed assign me this issue asap.

**Comment by prithvi206** [comment]
@akhil-rasheed assign this asap.

**Comment by prithvi206** [comment]
done.
